# Generated by Django 4.0.4 on 2022-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('is_client', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('goal', models.IntegerField()),
                ('donated', models.IntegerField(blank=True, default=0, null=True)),
                ('donator_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_amount', models.IntegerField()),
                ('account_number', models.CharField(max_length=20)),
                ('post', models.ManyToManyField(to='volunteerApp.post')),
                ('user', models.ManyToManyField(to='volunteerApp.member')),
            ],
        ),
    ]
